export enum TelemetryEventPriority {
  "Critical" = "Critical",
  "High" = "High",
  "Medium" = "Medium",
  "Low" = "Low",
}

// List of event names
export enum TelemetryEvents {
  "Datapilot/Feedback" = "Datapilot/Feedback",
  "DocumentationEditor/Load" = "DocumentationEditor/Load",
  "DocumentationEditor/SyncWithDBClick" = "DocumentationEditor/SyncWithDBClick",
  "DocumentationEditor/TestsTabClick" = "DocumentationEditor/TestsTabClick",
  "DocumentationEditor/SettingsOpen" = "DocumentationEditor/SettingsOpen",
  "DocumentationEditor/SettingsUpdate" = "DocumentationEditor/SettingsUpdate",
  "DocumentationEditor/HelpOpen" = "DocumentationEditor/HelpOpen",
  "DocumentationEditor/HelpTestsOpen" = "DocumentationEditor/HelpTestsOpen",
  "DocumentationEditor/HelpDocumentationLinkInDocumentationClick" = "DocumentationEditor/HelpDocumentationLinkInDocumentationClick",
  "DocumentationEditor/HelpContactusLinkInDocumentationClick" = "DocumentationEditor/HelpContactusLinkInDocumentationClick",
  "DocumentationEditor/HelpDocumentationLinkInTestsClick" = "DocumentationEditor/HelpDocumentationLinkInTestsClick",
  "DocumentationEditor/HelpContactusLinkInTestsClick" = "DocumentationEditor/HelpContactusLinkInTestsClick",
  "DocumentationEditor/FeedbackClick" = "DocumentationEditor/FeedbackClick",
  "DocumentationEditor/BulkGenerateTests" = "DocumentationEditor/BulkGenerateTests",
  "DocumentationEditor/SaveClick" = "DocumentationEditor/SaveClick",
  "DocumentationEditor/SaveBulk" = "DocumentationEditor/SaveBulk",
  "DocumentationEditor/SaveError" = "DocumentationEditor/SaveError",
  "DocumentationEditor/SaveNewFilePathSelect" = "DocumentationEditor/SaveNewFilePathSelect",
  "DocumentationEditor/BulkGenerateAllClick" = "DocumentationEditor/BulkGenerateAllClick",
  "DocumentationEditor/BulkGenerateAllError" = "DocumentationEditor/BulkGenerateAllError",
  "DocumentationEditor/BulkGenerateMissingColumnsClick" = "DocumentationEditor/BulkGenerateMissingColumnsClick",
  "DocumentationEditor/BulkGenerateMissingColumnsError" = "DocumentationEditor/BulkGenerateMissingColumnsError",
  "DocumentationEditor/GenerateDescForModelClick" = "DocumentationEditor/GenerateDescForModelClick",
  "DocumentationEditor/GenerateDescForColumnClick" = "DocumentationEditor/GenerateDescForColumnClick",
  "DocumentationEditor/GenerateDescByDatapilotForModelClick" = "DocumentationEditor/GenerateDescByDatapilotForModelClick",
  "DocumentationEditor/GenerateDescByDatapilotForColumnClick" = "DocumentationEditor/GenerateDescByDatapilotForColumnClick",
  "DocumentationEditor/ColumnTestClick" = "DocumentationEditor/ColumnTestClick",
  "DocumentationEditor/ModelTestClick" = "DocumentationEditor/ModelTestClick",
  "DocumentationEditor/AddTestClick" = "DocumentationEditor/AddTestClick",
  "DocumentationEditor/AddCustomTestClick" = "DocumentationEditor/AddCustomTestClick",
  "DocumentationEditor/GetDistinctColumnValues" = "DocumentationEditor/GetDistinctColumnValues",
  "DocumentationEditor/AcceptedValuesSaveClick" = "DocumentationEditor/AcceptedValuesSaveClick",
  "DocumentationEditor/RelationshipsToSelect" = "DocumentationEditor/RelationshipsToSelect",
  "DocumentationEditor/RelationshipsFieldSelect" = "DocumentationEditor/RelationshipsFieldSelect",
  "DocumentationEditor/RelationshipsSaveClick" = "DocumentationEditor/RelationshipsSaveClick",
  "DocumentationEditor/TestEditClick" = "DocumentationEditor/TestEditClick",
  "DocumentationEditor/TestEditCancel" = "DocumentationEditor/TestEditCancel",
  "DocumentationEditor/TestEditUpdateClick" = "DocumentationEditor/TestEditUpdateClick",
  "DocumentationEditor/TestDeleteClick" = "DocumentationEditor/TestDeleteClick",
  "DocumentationEditor/AddTestSelect" = "DocumentationEditor/AddTestSelect",
  "Notebook/DependenciesInstallCancelled" = "Notebook/DependenciesInstallCancelled",
  "Notebook/DependenciesInstalled" = "Notebook/DependenciesInstalled",
  "Notebook/DependenciesInstallError" = "Notebook/DependenciesInstallError",
  "Notebook/KernelInitializationError" = "Notebook/KernelInitializationError",
  "Notebook/KernelCloseError" = "Notebook/KernelCloseError",
  "Notebook/Execute" = "Notebook/Execute",
  "Notebook/WidgetVersionError" = "Notebook/WidgetVersionError",
  "Notebook/SaveError" = "Notebook/SaveError",
  "Notebook/Launch" = "Notebook/Launch",
  "Notebook/LaunchError" = "Notebook/LaunchError",
  "Notebook/StoreDataInKernelError" = "Notebook/StoreDataInKernelError",
  "QueryHistory/Disabled" = "QueryHistory/Disabled",
  "QueryHistory/ClearError" = "QueryHistory/ClearError",
  "CteProfiler/Profile" = "CteProfiler/Profile",
  "CteProfiler/Cancel" = "CteProfiler/Cancel",
  "MCP/ToolCall" = "MCP/ToolCall",
  "MCP/Onboarding" = "MCP/Onboarding",
  "MCP/Onboarding/SetUpNow" = "MCP/Onboarding/SetUpNow",
  "MCP/Onboarding/Later" = "MCP/Onboarding/Later",
  "MCP/Onboarding/Success" = "MCP/Onboarding/Success",
  "MCP/Onboarding/Failed" = "MCP/Onboarding/Failed",
  "AltimateCode/RunFailureClick" = "AltimateCode/RunFailureClick",
  "AltimateCode/CommandFailureClick" = "AltimateCode/CommandFailureClick",
  "AltimateCode/SqlValidationFixClick" = "AltimateCode/SqlValidationFixClick",
  "AltimateCode/ValidateSqlManifestErrorClick" = "AltimateCode/ValidateSqlManifestErrorClick",
  "AltimateCode/ValidateSqlCompileErrorClick" = "AltimateCode/ValidateSqlCompileErrorClick",
  "AltimateCode/ExplainTestFailureClick" = "AltimateCode/ExplainTestFailureClick",
  "AltimateCode/RunHistoryFixClick" = "AltimateCode/RunHistoryFixClick",
  "AltimateCode/TroubleshootCodeActionClick" = "AltimateCode/TroubleshootCodeActionClick",
  "DocumentationEditor/UnitTestGenerateClick" = "DocumentationEditor/UnitTestGenerateClick",
  "WhatsNew/PageOpened" = "whats_new_page_opened",
  // Carries a `source` so the three changelog links (topbar, hero CTA, footer,
  // plus the error state) can be told apart.
  "WhatsNew/FullChangelogClicked" = "full_changelog_clicked",
  // Which change types readers actually care about. This is the per-item
  // interest signal now that entries aren't links — the linked changelog entry
  // only repeats what the panel already shows, so there was nothing to click
  // through to.
  "WhatsNew/FilterToggled" = "whats_new_filter_toggled",
  // Whether the timeline rail earns the space it takes.
  "WhatsNew/TimelineNavigated" = "whats_new_timeline_navigated",
  // Cross-promo: the "Also from Altimate AI" aside exists to drive discovery.
  "WhatsNew/ProductLinkClicked" = "whats_new_product_link_clicked",
  "WhatsNew/SiteLinkClicked" = "whats_new_site_link_clicked",
  "QueryPanel/OptimizeWarehouseClick" = "QueryPanel/OptimizeWarehouseClick",
}
