import { expect } from "@jest/globals";
import * as fs from "fs";
import * as path from "path";

/**
 * Compatibility tests for @jupyterlab/services v7.
 *
 * These verify that all APIs used by the notebook kernel integration
 * (src/lib/index.js) are available and have the expected shape after
 * upgrading from v6 to v7.
 */

// ---------------------------------------------------------------------------
// 1. Public API surface
// ---------------------------------------------------------------------------

describe("@jupyterlab/services v7 API compatibility", () => {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const services = require("@jupyterlab/services");

  describe("ServerConnection", () => {
    it("should export ServerConnection", () => {
      expect(services.ServerConnection).toBeDefined();
    });

    it("should provide makeSettings()", () => {
      expect(typeof services.ServerConnection.makeSettings).toBe("function");
    });

    it("makeSettings() should return an object with expected properties", () => {
      const settings = services.ServerConnection.makeSettings({
        wsUrl: "RAW",
      });
      expect(settings).toBeDefined();
      expect(settings.wsUrl).toBe("RAW");
    });
  });

  describe("KernelConnection", () => {
    it("should export KernelConnection as a constructor", () => {
      expect(typeof services.KernelConnection).toBe("function");
    });
  });

  describe("KernelMessage type guards", () => {
    const expectedMethods = [
      "isCommOpenMsg",
      "isExecuteResultMsg",
      "isExecuteInputMsg",
      "isStatusMsg",
      "isStreamMsg",
      "isDisplayDataMsg",
      "isUpdateDisplayDataMsg",
      "isClearOutputMsg",
      "isErrorMsg",
      "isCommMsgMsg",
      "isCommCloseMsg",
    ];

    it("should export KernelMessage", () => {
      expect(services.KernelMessage).toBeDefined();
    });

    it.each(expectedMethods)("should provide KernelMessage.%s()", (method) => {
      expect(typeof services.KernelMessage[method]).toBe("function");
    });
  });
});

// ---------------------------------------------------------------------------
// 2. Internal modules used by the kernel bridge
// ---------------------------------------------------------------------------

describe("@jupyterlab/services internal modules", () => {
  it("should expose the serialize module", () => {
    const serialize = require("@jupyterlab/services/lib/kernel/serialize");
    expect(serialize).toBeDefined();
    expect(typeof serialize.serialize).toBe("function");
    expect(typeof serialize.deserialize).toBe("function");
  });

  it("should expose the nonSerializingKernel module (generated by postInstall)", () => {
    const nonSerializingKernel = require("@jupyterlab/services/lib/kernel/nonSerializingKernel");
    expect(nonSerializingKernel).toBeDefined();
    expect(nonSerializingKernel.KernelConnection).toBeDefined();
  });
});

// ---------------------------------------------------------------------------
// 3. postInstall kernel patching
// ---------------------------------------------------------------------------

describe("postInstall kernel patching", () => {
  const kernelDir = path.join(
    __dirname,
    "..",
    "..",
    "..",
    "node_modules",
    "@jupyterlab",
    "services",
    "lib",
    "kernel",
  );
  const defaultKernelPath = path.join(kernelDir, "default.js");
  const nonSerializingPath = path.join(kernelDir, "nonSerializingKernel.js");

  it("default.js should exist", () => {
    expect(fs.existsSync(defaultKernelPath)).toBe(true);
  });

  it("nonSerializingKernel.js should exist after postInstall", () => {
    expect(fs.existsSync(nonSerializingPath)).toBe(true);
  });

  it("nonSerializingKernel.js should have serialization stripped", () => {
    const contents = fs.readFileSync(nonSerializingPath, "utf8");
    // v7+: serverSettings.serializer calls should be replaced with pass-through
    expect(contents).not.toContain("this.serverSettings.serializer.serialize(");
    expect(contents).not.toContain(
      "this.serverSettings.serializer.deserialize(",
    );
    // v6: standalone serialize import should be replaced with no-op
    expect(contents).not.toMatch(
      /const serialize = __importStar\(require\("\.\/serialize"\)\)/,
    );
  });

  it("nonSerializingKernel.js should use parentHeader.session (not team.session)", () => {
    const contents = fs.readFileSync(nonSerializingPath, "utf8");
    expect(contents).toContain("parentHeader.session === this.clientId");
    expect(contents).not.toContain("team.session === this.clientId");
  });
});
