on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - created

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run common build steps
        uses: ./.github/actions/common-build

  release-vsstudio-marketplace:
    needs: build
    runs-on: ubuntu-latest
    if: success() && startsWith( github.ref, 'refs/tags/')
    strategy:
      fail-fast: false
      matrix:
        target:
          - darwin-arm64
          - darwin-x64
          - linux-arm64
          - linux-x64
          - win32-x64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run common build steps
        uses: ./.github/actions/common-build
        with:
          vsce-target: ${{ matrix.target }}
      - name: Publish Visual Studio Marketplace
        run: |
          PRE_RELEASE=""
          if [ "${{ github.event_name }}" == "release" ] && [ "${{ github.event.release.prerelease }}" == "true" ]; then
            PRE_RELEASE="--pre-release"
          fi
          npx vsce publish --skip-duplicate --target ${{ matrix.target }} $PRE_RELEASE
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          VSCE_TARGET: ${{ matrix.target }}

    # Send notification after all platform builds (only on the last matrix entry)
  release-vsstudio-notify:
    runs-on: ubuntu-latest
    needs: release-vsstudio-marketplace
    if: always() && startsWith( github.ref, 'refs/tags/')
    steps:
      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ needs.release-vsstudio-marketplace.result }}
          text: "Tag: ${{  github.ref_name }} release to Visual Studio Marketplace status: ${{ needs.release-vsstudio-marketplace.result == 'success' && 'succeeded' || 'failed' }} :${{ needs.release-vsstudio-marketplace.result == 'success' && 'tada' || 'disappointed' }}:"

  release-openvsx-marketplace:
    needs: build
    runs-on: ubuntu-latest
    if: success() && startsWith( github.ref, 'refs/tags/')
    strategy:
      fail-fast: false
      matrix:
        target:
          - darwin-arm64
          - darwin-x64
          - linux-arm64
          - linux-x64
          - win32-x64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run common build steps
        uses: ./.github/actions/common-build
        with:
          vsce-target: ${{ matrix.target }}
      - name: Publish OpenVSX Marketplace
        run: |
          PRE_RELEASE=""
          if [ "${{ github.event_name }}" == "release" ] && [ "${{ github.event.release.prerelease }}" == "true" ]; then
            PRE_RELEASE="--pre-release"
          fi
          npx ovsx publish --skip-duplicate --target ${{ matrix.target }} $PRE_RELEASE
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
          VSCE_TARGET: ${{ matrix.target }}

  release-openvsx-notify:
    runs-on: ubuntu-latest
    needs: release-openvsx-marketplace
    if: always() && startsWith( github.ref, 'refs/tags/')
    steps:
      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ needs.release-openvsx-marketplace.result }}
          text: "Tag: ${{  github.ref_name }} release to openvsx marketplace status: ${{ needs.release-openvsx-marketplace.result == 'success' && 'succeeded' || 'failed' }} :${{ needs.release-openvsx-marketplace.result == 'success' && 'tada' || 'disappointed' }}:"
