name: Release

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install
      - run: npm install
        working-directory: ./new_lineage_panel
      - run: npm install
        working-directory: ./webview_panels
      - name: Debugging info
        run: |
          echo "Ref: ${{ github.ref }}"
          echo "Is Prerelease: ${{ github.event.release.prerelease }}"
  release-vsstudio-marketplace:
    needs: build
    steps:
      - name: Publish Visual Studio Marketplace
        if: success() && startsWith( github.ref, 'refs/tags/')
        run: |
          if [ "${{ github.event_name }}" == "release" ] && [ "${{ github.event.release.prerelease }}" == "true" ]; then
            npm run deploy-vscode -- --pre-release
          else
            npm run deploy-vscode
          fi
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
  release-openvsx-marketplace:
    needs: build
    steps:
      - name: Publish OpenVSX Marketplace
        if: success() && startsWith( github.ref, 'refs/tags/')
        run: |
          if [ "${{ github.event_name }}" == "release" ] && [ "${{ github.event.release.prerelease }}" == "true" ]; then
            npm run deploy-openvsx -- --pre-release
          else
            npm run deploy-openvsx
          fi
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
