name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        npm run install:panels

    - name: Compile
      run: npm run compile

    - name: Install xvfb
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb

    - name: Run tests (Linux)
      if: runner.os == 'Linux'
      run: |
        xvfb-run --auto-servernum npm run test
        xvfb-run --auto-servernum npm run test:unit

    - name: Run tests (macOS/Windows)
      if: runner.os != 'Linux'
      run: |
        npm run test
        npm run test:unit

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results-${{ matrix.os }}
        path: test-results/ 